scrape_configs:
  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'namespace'
        replacement: 'local-dev'
      - source_labels: ['__address__']
        target_label: 'app'
        replacement: 'django-app'

  - job_name: 'nextjs'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']

